CREATE TABLE `data_platform_contract_item_data`
(
    `Contract`                                          int(16) NOT NULL,
    `ContractItem`                                      int(6) NOT NULL,
    `ContractItemCategory`                              varchar(4) NOT NULL,
    `ContractStatus`                                    varchar(3) NOT NULL,
    `SupplyChainRelationshipID`                         int(16) NOT NULL,
    `SupplyChainRelationshipDeliveryID`                 int(6) DEFAULT NULL,
    `SupplyChainRelationshipDeliveryPlantID`            int(4) DEFAULT NULL,
    `SupplyChainRelationshipProductionPlantID`          int(4) DEFAULT NULL,
    `Buyer`                                             int(12) NOT NULL,
    `Seller`                                            int(12) NOT NULL,
    `DeliverToParty`                                    int(12) DEFAULT NULL,
    `DeliverFromParty`                                  int(12) DEFAULT NULL,
    `DeliverToPlant`                                    varchar(4) DEFAULT NULL,
    `DeliverFromPlant`                                  varchar(4) DEFAULT NULL,
    `ContractItemText`                                  varchar(200) NOT NULL,
    `ContractItemTextByBuyer`                           varchar(200) NOT NULL,
    `ContractItemTextBySeller`                          varchar(200) NOT NULL,
    `Product`                                           varchar(40) NOT NULL,
    `SizeOrDimensionText`                               varchar(100) DEFAULT NULL,
    `ProductStandardID`                                 varchar(18) DEFAULT NULL,
    `ProductGroup`                                      varchar(9) DEFAULT NULL,
	`ProductSpecification`		 	                    varchar(200) DEFAULT NULL,
    `MarkingOfMaterial`                                 varchar(100) DEFAULT NULL,
    `BaseUnit`                                          varchar(3) NOT NULL,
    `DeliveryUnit`                                      varchar(3) DEFAULT NULL,
    `ProductionVersion`                                 int(16) DEFAULT NULL,
    `ProductionVersionItem`                             int(6) DEFAULT NULL,
    `BillOfMaterial`                                    int(16) DEFAULT NULL,
    `BillOfMaterialItem`                                int(6) DEFAULT NULL,
    `PricingDate`                                       date DEFAULT NULL,
    `PriceDetnExchangeRate`                             float(8) DEFAULT NULL,
    `ServicesRenderingDate`                             date DEFAULT NULL,
    `ContractQuantityInBaseUnit`                        float(15) DEFAULT NULL,
    `ContractQuantityInDeliveryUnit`                    float(15) DEFAULT NULL,
    `QuantityPerPackage`                                float(15) DEFAULT NULL,
    `InternalCapacityQuantity`                          float(15) DEFAULT NULL,
    `InternalCapacityQuantityUnit`                      varchar(3) DEFAULT NULL,
    `NetAmount`                                         float(13) NOT NULL,
    `TaxAmount`                                         float(13) NOT NULL,
    `GrossAmount`                                       float(13) NOT NULL,
    `InvoiceDocumentDate`                               date DEFAULT NULL,
    `ProductionPlantBusinessPartner`                    int(12) DEFAULT NULL,
    `ProductionPlant`                                   varchar(4) DEFAULT NULL,
    `InspectionPlantBusinessPartner`                    int(12) DEFAULT NULL,
    `InspectionPlant`                                   varchar(4) DEFAULT NULL,
    `InspectionPlan`                                    int(16) DEFAULT NULL,
    `InspectionLot`                                     int(16) DEFAULT NULL,
    `TransactionTaxClassification`                      varchar(1) NOT NULL,
    `ProductTaxClassificationBillToCountry`             varchar(1) NOT NULL,
    `ProductTaxClassificationBillFromCountry`           varchar(1) NOT NULL,
    `DefinedTaxClassification`                          varchar(1) NOT NULL,
    `AccountAssignmentGroup`                            varchar(2) NOT NULL,
    `ProductAccountAssignmentGroup`                     varchar(2) NOT NULL,
    `PaymentTerms`                                      varchar(4) NOT NULL,
    `DueCalculationBaseDate`                            date DEFAULT NULL,
    `PaymentDueDate`                                    date DEFAULT NULL,
    `NetPaymentDays`                                    int(3) DEFAULT NULL,
    `PaymentMethod`                                     varchar(1) NOT NULL,
    `Project`                                           int(16) DEFAULT NULL,
    `WBSElement`                                        int(8) DEFAULT NULL,
    `AccountingExchangeRate`                            float(8) DEFAULT NULL,
    `TaxCode`                                           varchar(1) DEFAULT NULL,
    `TaxRate`                                           float(6) DEFAULT NULL,
    `CountryOfOrigin`                                   varchar(3) DEFAULT NULL,
    `CountryOfOriginLanguage`                           varchar(2) DEFAULT NULL,
    `Equipment`                                         int(20) DEFAULT NULL,
    `ItemBlockStatus`                                   tinyint(1) DEFAULT NULL,
    `ExternalReferenceDocument`                         varchar(100) DEFAULT NULL,
    `ExternalReferenceDocumentItem`                     varchar(10) DEFAULT NULL,
    `CreationDate`                                      date NOT NULL,
    `CreationTime`                                      time NOT NULL,
    `LastChangeDate`                                    date NOT NULL,
    `LastChangeTime`                                    time NOT NULL,
    `IsCancelled`                                       tinyint(1) DEFAULT NULL,
    `IsMarkedForDeletion`                               tinyint(1) DEFAULT NULL,
    
    PRIMARY KEY (`Contract`, `ContractItem`),
    
    CONSTRAINT `DPFMContractItemData_fk` FOREIGN KEY (`Contract`) REFERENCES `data_platform_contract_header_data` (`Contract`),
    CONSTRAINT `DPFMContractItemDataSCRDID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_scr_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DPFMContractItemDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DPFMContractItemDataSCRDeliveryPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`) REFERENCES `data_platform_scr_delivery_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`),
    CONSTRAINT `DPFMContractItemDataSCRProductionPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`) REFERENCES `data_platform_scr_production_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`),
    CONSTRAINT `DPFMContractItemDataSCRDeliveryPlantProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_scr_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
    CONSTRAINT `DPFMContractItemDataSCRProductionPlantProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_scr_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
    CONSTRAINT `DPFMContractItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DPFMContractItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMContractItemDataDeliveryUnit_fk` FOREIGN KEY (`DeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMContractItemDataProductionVersionItem_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
    CONSTRAINT `DPFMContractItemDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`) REFERENCES `data_platform_bill_of_material_header_data` (`BillOfMaterial`),
    CONSTRAINT `DPFMContractItemDataBillOfMaterialItem_fk` FOREIGN KEY (`BillOfMaterial`, `BillOfMaterialItem`) REFERENCES `data_platform_bill_of_material_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
    CONSTRAINT `DPFMContractItemDataItemInternalCapacityQuantityUnit_fk` FOREIGN KEY (`InternalCapacityQuantityUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMContractItemDataInspectionPlant_fk` FOREIGN KEY (`InspectionPlantBusinessPartner`, `InspectionPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DPFMContractItemDataInspectionPlan_fk` FOREIGN KEY (`InspectionPlan`) REFERENCES `data_platform_inspection_plan_header_data` (`InspectionPlan`),
    CONSTRAINT `DPFMContractItemDataInspectionLot_fk` FOREIGN KEY (`InspectionLot`) REFERENCES `data_platform_inspection_lot_header_data` (`InspectionLot`),
    CONSTRAINT `DPFMContractItemDataPaymentMethod_fk` FOREIGN KEY (`PaymentMethod`) REFERENCES `data_platform_payment_method_payment_method_data` (`PaymentMethod`),
    CONSTRAINT `DPFMContractItemDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMContractItemDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
--  CONSTRAINT `DPFMContractItemDataTaxCode_fk` FOREIGN KEY (`TaxCode`) REFERENCES `data_platform_tax_code_tax_code_data` (`TaxCode`),
    CONSTRAINT `DPFMContractItemDataCountryOfOrigin_fk` FOREIGN KEY (`CountryOfOrigin`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMContractItemDataCountryOfOriginLanguage_fk` FOREIGN KEY (`CountryOfOriginLanguage`) REFERENCES `data_platform_language_language_data` (`Language`),
    CONSTRAINT `DPFMContractItemDataEquipment_fk` FOREIGN KEY (`Equipment`) REFERENCES `data_platform_equipment_master_general_data` (`Equipment`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
